sudo: required

services: 
  - docker

berfore_install:
  - echo leeeehkdaaaaleeeeeh

script:
  - echo "Leeeh ya nosa tedrabe loza"

after_sucess:
  - docker build -t kareemelkasaby/crowd_funding_webapp ./crowd_funding_webapp
  - docker build -t kareemelkasaby/django_project_nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  - docker push kareemelkasaby/crowd_funding_webapp
  - docker push kareemelkasaby/django_project_nginx

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "django-project"
    env: "django-project-env"
    bucket_name: "elasticbeanstalk-us-west-2-672223761426"
    bucket_path: "django-project"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY