version: '3'

services: 
  crowd-funding-webapp:
    image: kareemelkasaby/crowd_funding_webapp
    expose:
      - "8000"
  nginx:
    restart: always
    image: kareemelkasaby/django_project_nginx
    ports:
      - '80:80'
  