version: '3'

services: 
  crowd-funding-webapp:
    build: ./crowd-funding-webapp
    command: gunicorn fund.wsgi:application --bind 0.0.0.0:8000
    # env_file:
    #   - ./.env.dev
    expose:
      - "8000"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - '80:80'
  