version: '3'

services: 
  crowd-funding-webapp:
    build: ./crowd-funding-webapp
    command: gunicorn fund.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./crowd-funding-webapp/Project/static:/djangoApp/Project/static_cdn/static_root
      # - ./crowd-funding-webapp/Project/static/:/djangoApp/Project/static/
    # env_file:
    #   - ./.env.dev
    expose:
      - "8000"
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - ./crowd-funding-webapp/Project/static:/static
    ports:
      - '80:80'
  